title:              Literary Pilgrim
email:              javansdalmas@gmail.com
description:        A Blog By Nyawade Nyateng
author:             Nyawade Nyateng
baseurl:            "/literary-pilgrim"
url:                ""

# Social Profiles
twitter_username:   javansdalmas
github_username:    
facebook_username:  javansdalmas
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
